### ISSUE TITLE
Change the insertion hotsplot plot

### ISSUE THREAD

**Issue by hyunhwaj** [LiuzLab/TraceQC#14]
After having a discussion with @JasperYH, we've decided to change the circos plot for visualization of the insertion hotspot.

**Comment by hyunhwaj** [comment]
@JasperYH I thought you had code but haven't applied. Can you put the code?

**Comment by JasperYH** [comment]
Yes, I have that code. However, the Carlin paper plotted the same way we did, so I think maybe we don't need to change.

**Comment by hyunhwaj** [comment]
Then I will close the issue.
