### ISSUE TITLE
mutation_type function have a bug when running example_obj

### ISSUE THREAD

**Issue by JasperYH** [LiuzLab/TraceQC#18]

**Comment by hyunhwaj** [comment]
Can you specify the bug?

**Comment by JasperYH** [comment]
`> data(example_obj)
> mutation_type(example_obj)
Error: `breaks` and `labels` must have the same length
Run `rlang::last_error()` to see where the error occurred.
Called from: signal_abort(cnd)`

**Comment by JasperYH** [comment]
I already know the reason. The diversity of mutation is low in dataframe `example_obj$mutation`

**Comment by hyunhwaj** [comment]
Do you think we won't see the error when we execute the function on a real FASTQ file?

**Comment by JasperYH** [comment]
No, we won't. There are only 35 different types of mutations in the `example_obj`. Have you made any update to that object recently?

**Comment by hyunhwaj** [comment]
I did some when I was fixing the index issue. Can you test using objects after execution of the below snippet?

```
data(example_obj_list)
obj <- example_obj_list$day14
```

Please test using the `obj` value.

**Comment by JasperYH** [comment]
It works well
