### ISSUE TITLE
example_obj  is not available

### ISSUE THREAD

**Issue by MrCloud123** [LiuzLab/TraceQC#22]
> library(TraceQC)
> data(example_obj)
Warning message:
In data(example_obj) : data set ‘example_obj’ not found

I have install the package and run library(TraceQC) successfully, but still can not get the example_obj.
can someone send me one or tell me how to figure out the problem?

I have tried these code and it works, so it seem that some file is not available, but not my RStudio.
library(PRIME)
data(testdata)

**Comment by JasperYH** [comment]
The `example_obj` file has been removed. The latest tutorial is available at: 
https://liuzlab.github.io/TraceQC/tutorial
https://liuzlab.github.io/TraceQC/tutorial_sc

**Comment by zhandong** [comment]
Jingyuan. Please explain why the file was there the first place. This could be your reviewer

Sent from my iPhone

On Apr 16, 2022, at 2:11 PM, Jingyuan Hu ***@***.***> wrote:

﻿***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

Reopened #22<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LiuzLab_TraceQC_issues_22&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=uQkjX_JsX9iLl-KGtK5q_DqXiq-fiLsjhZ_wbwX_m38&m=Fvh4HOM5pcguPhP8Nxctm3_l4OHyZifnfFq9SRU-30oR_KbqBR6zFqV6HpxADOjy&s=ijQV0vlB0ShbNjHlxlcgkLh8Ly4aeaA_cAzgRSvPWQk&e=>.

**Comment by JasperYH** [comment]
Working on it.
________________________________

**Comment by JasperYH** [comment]
The documentation is updated.
